spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Employee
    username: root
    password: Ramesh@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: imap.gmail.com
    port: 993
    username: ramesh.eidiko@gmail.com
    password: wnzf sbqn qwnr kckc # Use App Password or OAuth2

logging:
  level:
    root: INFO
    org.springframework.jdbc.core: DEBUG
